openapi: 3.0.0
info:
  title: Notification Service
  description: |-
    Notification Service - это микросервис, который отвечает за отправку уведомлений пользователям.
  version: 0.0.0
servers:
  - url: http://localhost:18085
    description: Local Server URL
tags:
  - name: Email
    description: Эндпоинты для отправки писем по почте
paths:
  /api/v0/notification/email:
    post:
      tags:
        - Email
      summary: Отправка письма по почте
      description: Отправляет заданное сообщение с заданным заголовком заданному пользователю
      operationId: sendEmail
      security:
        - bearerAuth:
            - SEND_EMAIL
      responses:
        '200':
          description: Письмо успешно отправлено
        '400':
          description: Ошибка при отправке почты
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorDto'
              example:
                created_at: '2024-03-27T03:26:19.385Z'
                message: 'Ошибка при отправке почты.'
        '403':
          description: Нет доступа
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorDto'
              example:
                created_at: '2024-03-27T03:26:19.385Z'
                message: Access denied.
        '500':
          description: Ошибка на сервере
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorDto'
              example:
                created_at: '2024-03-27T03:26:19.385Z'
                message: 'Внутренняя ошибка сервера.'
  /api/v0/notification/email/template:
    post:
      tags:
        - Email
      summary: Отправка шаблонного письма
      description: |-
        Отправляет запрос к template-service для рендеринга и в случае успеха отправляет срендеренное сообщение с 
        заданным заголовком заданному пользователю
      operationId: sendTemplateEmail
      security:
        - bearerAuth:
            - SEND_EMAIL
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RenderDto'
        required: true
      responses:
        '200':
          description: Шаблон успешно создан
          content:
            'text/html':
              schema:
                type: string
                example: '<p>Привет, Василий!</p>'
        '400':
          description: Переданы неправильные аргументы шаблона; Ошибка при отправке почты
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorDto'
              examples:
                Аргументы дублируются:
                  description: Аргументы дублируются
                  value:
                    created_at: '2024-03-27T03:26:19.385Z'
                    message: 'Недопустимые аргументы шаблона: аргументы дублируются.'
                Пропущен обязательный аргумент:
                  description: Пропущен обязательный аргумент
                  value:
                    created_at: '2024-03-27T03:26:19.385Z'
                    message: 'Недопустимые аргументы шаблона: отсутствует обязательный аргумент.'
                Передан лишний аргумент:
                  description: Передан лишний аргумент
                  value:
                    created_at: '2024-03-27T03:26:19.385Z'
                    message: 'Недопустимые аргументы шаблона: передан лишний аргумент.'
                Ошибка при отправке почты:
                  description: Ошибка при отправке почты.
                  value:
                    created_at: '2024-03-27T03:26:19.385Z'
                    message: 'Ошибка при отправке почты.'
        '403':
          description: Нет доступа
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorDto'
              example:
                created_at: '2024-03-27T03:26:19.385Z'
                message: Access denied.
        '404':
          description: Шаблон не найден
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorDto'
              example:
                created_at: '2024-03-27T03:26:19.385Z'
                message: Template not found.
        '500':
          description: Ошибка на сервере
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorDto'
              example:
                created_at: '2024-03-27T03:26:19.385Z'
                message: Internal server error.
components:
  schemas:
    ErrorDto:
      required:
        - created_at
        - message
      type: object
      properties:
        message:
          type: string
          description: Сообщение ошибки
          example: 'Ошибка проверки:'
        errors:
          type: object
          additionalProperties:
            type: string
            description: Название поля и его ошибки
            example: '{"code":"Код шаблона должен состоять из строчных латинских букв, цифр и подчеркиваний."}'
          description: Название поля и его ошибки
        created_at:
          type: string
          description: Время создания
          format: date-time
          example: '2024-03-27T03:57:26.951Z'
    RenderDto:
      required:
        - code
      type: object
      properties:
        code:
          type: string
          description: Код шаблона
          example: 'activation_account_message'
        parameters:
          type: array
          items:
            required:
              - name
              - value
            type: object
            properties:
              name:
                type: string
                description: Название параметра
                example: 'first_name'
              value:
                type: string
                description: Значение параметра
                example: 'Василий'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT